#!/bin/bash
# Build a Memory Map.app bundle that launches the dev server and opens
# the browser. Run this once per clone (or after moving the repo).
#
# Usage:
#   ./apps/macos-launcher/build.sh                  # → /Applications/Memory Map.app
#   ./apps/macos-launcher/build.sh ~/Applications   # → ~/Applications/Memory Map.app
#
# Requires macOS (uses sips + iconutil + LaunchServices).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
DEST_DIR="${1:-/Applications}"
APP_PATH="$DEST_DIR/Memory Map.app"
ICON_SRC="$SCRIPT_DIR/icon-1024.png"

if [[ ! -f "$ICON_SRC" ]]; then
  echo "Icon source not found: $ICON_SRC" >&2
  exit 1
fi

if [[ ! -d "$DEST_DIR" ]]; then
  echo "Destination directory does not exist: $DEST_DIR" >&2
  exit 1
fi

# Detect node@22. better-sqlite3 won't build on Node 25.
NODE22_BIN=""
for candidate in /opt/homebrew/opt/node@22/bin /usr/local/opt/node@22/bin; do
  if [[ -x "$candidate/node" ]]; then
    NODE22_BIN="$candidate"
    break
  fi
done

if [[ -z "$NODE22_BIN" ]]; then
  echo "Warning: node@22 not found via Homebrew. The launcher will fall back" >&2
  echo "to whatever 'node' is on PATH, which may be too new for better-sqlite3." >&2
  echo "Install with: brew install node@22" >&2
  NODE22_BIN="/opt/homebrew/opt/node@22/bin"
fi

echo "Building Memory Map.app"
echo "  repo:  $REPO_DIR"
echo "  dest:  $APP_PATH"
echo "  node:  $NODE22_BIN"

# Wipe any previous build
rm -rf "$APP_PATH"
mkdir -p "$APP_PATH/Contents/MacOS" "$APP_PATH/Contents/Resources"

# --- Info.plist ---
cat > "$APP_PATH/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>Memory Map</string>
    <key>CFBundleDisplayName</key>
    <string>Memory Map</string>
    <key>CFBundleIdentifier</key>
    <string>com.memorymap.launcher</string>
    <key>CFBundleVersion</key>
    <string>0.1.0</string>
    <key>CFBundleShortVersionString</key>
    <string>0.1.0</string>
    <key>CFBundleExecutable</key>
    <string>memory-map</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>LSMinimumSystemVersion</key>
    <string>10.13</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
</dict>
</plist>
PLIST

# --- Launcher script ---
cat > "$APP_PATH/Contents/MacOS/memory-map" <<EOF
#!/bin/bash
# Memory Map launcher — generated by apps/macos-launcher/build.sh
# Starts \`pnpm dev\` in the repo, waits for the web server to come up,
# opens the browser, and stays alive so quitting the app stops the server.

set -u

REPO_DIR="$REPO_DIR"
LOG_DIR="\$HOME/Library/Logs/Memory Map"
LOG_FILE="\$LOG_DIR/memory-map.log"
WEB_URL="http://localhost:5173"

mkdir -p "\$LOG_DIR"

# node@22 is required for better-sqlite3
export PATH="$NODE22_BIN:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"

cd "\$REPO_DIR" || {
  /usr/bin/osascript -e "display alert \"Memory Map\" message \"Repo not found at \$REPO_DIR\""
  exit 1
}

{
  echo ""
  echo "=== \$(date) launcher start ==="
} >> "\$LOG_FILE"

set -m
pnpm dev >> "\$LOG_FILE" 2>&1 &
DEV_PID=\$!
set +m

cleanup() {
  if kill -0 "\$DEV_PID" 2>/dev/null; then
    kill -TERM -"\$DEV_PID" 2>/dev/null || kill -TERM "\$DEV_PID" 2>/dev/null
    for _ in 1 2 3 4 5; do
      kill -0 "\$DEV_PID" 2>/dev/null || break
      sleep 0.5
    done
    kill -KILL -"\$DEV_PID" 2>/dev/null || kill -KILL "\$DEV_PID" 2>/dev/null
  fi
}
trap cleanup EXIT INT TERM HUP

# Wait up to 60s for Vite to come up
for _ in \$(seq 1 120); do
  if /usr/bin/curl -sf -o /dev/null "\$WEB_URL"; then
    break
  fi
  if ! kill -0 "\$DEV_PID" 2>/dev/null; then
    /usr/bin/osascript -e "display alert \"Memory Map\" message \"Dev server failed to start. See \$LOG_FILE\""
    exit 1
  fi
  sleep 0.5
done

/usr/bin/open "\$WEB_URL"

wait "\$DEV_PID"
EOF
chmod +x "$APP_PATH/Contents/MacOS/memory-map"

# --- Icon ---
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/Icon.iconset"
sips -s format png -z 16 16     "$ICON_SRC" --out "$WORK/Icon.iconset/icon_16x16.png"     >/dev/null
sips -s format png -z 32 32     "$ICON_SRC" --out "$WORK/Icon.iconset/icon_16x16@2x.png"  >/dev/null
sips -s format png -z 32 32     "$ICON_SRC" --out "$WORK/Icon.iconset/icon_32x32.png"     >/dev/null
sips -s format png -z 64 64     "$ICON_SRC" --out "$WORK/Icon.iconset/icon_32x32@2x.png"  >/dev/null
sips -s format png -z 128 128   "$ICON_SRC" --out "$WORK/Icon.iconset/icon_128x128.png"   >/dev/null
sips -s format png -z 256 256   "$ICON_SRC" --out "$WORK/Icon.iconset/icon_128x128@2x.png" >/dev/null
sips -s format png -z 256 256   "$ICON_SRC" --out "$WORK/Icon.iconset/icon_256x256.png"   >/dev/null
sips -s format png -z 512 512   "$ICON_SRC" --out "$WORK/Icon.iconset/icon_256x256@2x.png" >/dev/null
sips -s format png -z 512 512   "$ICON_SRC" --out "$WORK/Icon.iconset/icon_512x512.png"   >/dev/null
sips -s format png -z 1024 1024 "$ICON_SRC" --out "$WORK/Icon.iconset/icon_512x512@2x.png" >/dev/null
iconutil -c icns "$WORK/Icon.iconset" -o "$APP_PATH/Contents/Resources/AppIcon.icns"

# Tell LaunchServices to re-read the bundle so Finder/Spotlight pick up the new icon
LSREGISTER=/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister
if [[ -x "$LSREGISTER" ]]; then
  "$LSREGISTER" -f "$APP_PATH" >/dev/null 2>&1 || true
fi
touch "$APP_PATH"

echo ""
echo "Done. Launch with:"
echo "  open -a \"Memory Map\""
echo "or double-click $APP_PATH"
